#!/usr/bin/env bash
#===============================================================================
#
#          FILE: git-conflicts
#
#         USAGE: git conflicts
#                For more info, see the docs below in the usage function.
#
#   DESCRIPTION: Compare two branches for possible merge conflicts.
#                See git_conflict_parser.py for more info.
#
#  REQUIREMENTS: git
#
#        AUTHOR: Elliott Indiran <elliott.indiran@protonmail.com>
#===============================================================================
set -Eeuo pipefail

usage() {
    # Print usage info
    cat <<EOF
        USAGE: git conflicts [-s | --show] [-n | --no-colors] [<BRANCH1>] <BRANCH2>
               git conflicts [-f | --files] [<BRANCH1>] <BRANCH2>
               git conflicts -h

  DESCRIPTION:
               Compare two branches for possible merge conflicts.
               See git_conflict_parser.py for more info.
     EXAMPLES:
               'git conflicts <BRANCH1> <BRANCH2>' ->
                    Find whether BRANCH1 and BRANCH2 would have merge conflicts.
               'git conflicts <BRANCH2>' ->
                    Find whether the current branch and BRANCH2 would have merge conflicts.
               'git conflicts --show <BRANCH1> <BRANCH2>' ->
                    Show the full list of conflicts between BRANCH1 and BRANCH2,
                    colorized.
               'git conflicts -s <BRANCH2>' ->
                    Show the full list of conflicts between the current branch and BRANCH2,
                    colorized.
               'git conflicts --show --no-colors <BRANCH1> <BRANCH2>' ->
                    Show the full list of conflicts between BRANCH1 and BRANCH2,
                    *not* colorized.
               'git conflicts -f <BRANCH1> <BRANCH2>' ->
                    Show the filenames between BRANCH1 and BRANCH2 that
                    contain conflicts.
EOF

}

create_tempfile() {
    # Helper function for creating tempfiles
    tempprefix=$(basename "$0")
    mktemp "/tmp/${tempprefix}.XXXXXXXX"
}

SHOW_CONFLICTS_MODE=false
FILENAME_MODE=false
NO_COLOR_MODE=false
DEBUG_MODE=false

PARSED_ARGUMENTS=$(getopt -a -n gitconflicts -o sfnh --long show,files,no-colors,help -- "$@")
VALID_PARSE=$?
if [ "$VALID_PARSE" != 0 ]; then
    # getopt failed to parse the args correctly
    usage
    exit 2
fi
if $DEBUG_MODE ; then
    echo "${PARSED_ARGUMENTS}"
fi
eval set -- "$PARSED_ARGUMENTS"
while :
do
    case "$1" in
        -s | --show)
            SHOW_CONFLICTS_MODE=true
            shift
            ;;
        -f | --files)
            FILENAME_MODE=true
            shift
            ;;
        -n | --no-colors)
            NO_COLOR_MODE=true
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            printf "Invalid option: %s\n" "$1"
            usage
            exit 2
            ;;
    esac
done

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    printf "Must specify 1 or 2 branches names; %d specified instead\n" "$#"
    usage
    exit 2
fi
if [ "$#" -eq 1 ]; then
    BRANCH1="$(git branch --show-current)"
    BRANCH2="${1}"
else
    BRANCH1="${1}"
    BRANCH2="${2}"
fi
GIT_OUTPUT_TEMPFILE="$(create_tempfile)"
trap 'rm -f "${GIT_OUTPUT_TEMPFILE}"' EXIT
git merge-tree "$(git merge-base "${BRANCH1}" "${BRANCH2}")" "${BRANCH1}" "${BRANCH2}" > "${GIT_OUTPUT_TEMPFILE}"

if $SHOW_CONFLICTS_MODE ; then
    if $NO_COLOR_MODE ; then
        git_conflict_parser.py -f "${GIT_OUTPUT_TEMPFILE}"
    else
        git_conflict_parser.py -f "${GIT_OUTPUT_TEMPFILE}" -C
    fi
elif $FILENAME_MODE ; then
    git_conflict_parser.py -f "${GIT_OUTPUT_TEMPFILE}" -c
else
    git_conflict_parser.py -f "${GIT_OUTPUT_TEMPFILE}" -x
fi
