#!/usr/bin/env python3
'''
git_conflict_parser.py

Read in a diff from a merge-tree, and show the conflicts
split up by file.
'''
import argparse
import re
from typing import List, Match, Optional, Pattern


# GLOBALS:
FILEPATH_REGEX: Pattern = re.compile('^\s+base\s+[0-9]+\s+[a-fA-F0-9]+\s+(.*?)$')
START_REGEX: Pattern = re.compile(r'+<<<<<<< .our')
END_REGEX: Pattern = re.compile(r'+>>>>>>> .their')
DEFAULT_ENCODING: str = 'utf8'


def _output(output_file: Optional[IO], text: str) -> None:
    '''
    Output function -- will either write to a specified file object,
    or to stdout if the filename is None.
    '''
    output_file.write(text) if output_file else print(text)


def conflict_parser(
        filename: str,
        output_file: Optional[str],
        encoding: str=DEFAULT_ENCODING) -> None:
    '''
    Parse conflicts for the merge of two branches foo and bar
    out of the output of:
        `git merge-tree $(git merge-base foo bar) foo bar`
    Generate a conflict diff (or print to stdout).
    '''
    lines: List[str] = []
    o: Optional[IO] = None
    currently_matching: bool = False
    with open(filename, 'r', encoding=encoding) as f:
        for line in f:
            lines.append(line)
    if output_file:
        o = open(output_file, 'w', encoding=encoding)
    for line in lines:
        m: Match = re.match(FILEPATH_REGEX, line)
        if m:
            _output(o, m.groups(0) + '\n')
        elif currently_matching:
            _output(o, line)
        elif re.match(START_REGEX, line):
            currently_matching = True
            _output(o, line)
        elif re.match(END_REGEX, line):
            currently_matching = False
            _output(o, line)
    _output(o, '') # Final newline in file.
    if o:
        o.close()


def main():
    '''
    Arg parser.
    '''
    parser = argparse.ArgumentParser(
        description='Parse a diff generated by `git merge-tree` ' +
        'for conflicts in a potential `git merge` between two branches'
    )
    # parser.add_argument('branch1', type=str, required=True)
    # parser.add_argument('branch2', type=str, required=True)
    parser.add_argument(
        '-f',
        '--file',
        dest='filename',
        type=str,
        required=True,
        help='Path to a file containing the diff generated by `git merge-tree`'
    )
    parser.add_argument(
        '-e',
        '--encoding',
        dest='encoding',
        type=str,
        required=False,
        help='Encoding of specified file. Default: UTF-8'
    )
    parser.add_argument(
        '-o',
        '--output_file',
        dest='output_file',
        type=str,
        required=False,
        help='Optional filename to write the resulting conflict diff to. Default: STDOUT'
    )
    args = parser.parse_args()
    kwargs = {
    conflict_parser(args.filename, args.output_file, args.encoding)




if __name__ == '__main__':
    main()
